server:
  port: 8083

spring:

  application:
    name: queue-service

  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB:sinapse}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}

  jpa:

    hibernate:
      ddl-auto: update

    properties:

      hibernate:
        default_schema: queue
        format_sql: true

    show-sql: false
  
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASSWORD:guest}

logging:
  level:
    br.com.sinapse.queue: INFO

triage-event:
  exchange: ${TRIAGE_EVENT_EXCHANGE:triage.exchange}
  routing-key: ${TRIAGE_EVENT_ROUTING_KEY:triage.completed}
  queue: ${TRIAGE_EVENT_QUEUE:triage.completed.queue}
