server:
  port: 8081

spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB:sinapse}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}

  jpa:

    hibernate:
      ddl-auto: update

    properties:

      hibernate:
        default_schema: patient
        format_sql: true



    show-sql: false

  rabbitmq:
    host: localhost
    port: 5672
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASSWORD:guest}